{
  "model": "o4-mini",
  "provider": "azure",
  "providers": {
    "azure": {
      "name": "azure",
      "baseURL": "https://api.githubcopilot.com/chat/completions",
      "envKey": "AZURE_OPENAI_API_KEY"
    }
  },
  "history": {
    "maxSize": 1000,
    "saveHistory": true,
    "sensitivePatterns": []
  }
}